### ISSUE TITLE
A connection attempt failed because the connected party did not properly respond after a period of time,

### ISSUE THREAD

**Issue by hp0123** [kolsrud/qlik_rest_sdk#1]
I get this exception - 
Inner Exception 1:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 

In the main below is what I have:
            var senseServerUrl = args.Any() ? args[0] : "https://myserverURL:4242";
            var restClient = new RestClient(senseServerUrl);            
            restClient.LoadCertificateFromDirectory(@"C:\certs\certFolder");
            restClient.AsNtlmUserViaProxy();            
            Console.WriteLine(restClient.Get("/qrs/about"));

**Comment by kolsrud** [comment]
Looks like you are mixing the connection types. Port number and certificates are only necessary if you do a direct connection.

Anyway, I just pushed a few fixes that affects both how you collect certificates and how NTLM connections are performed, so you should probably update to the latest one.

**Comment by hp0123** [comment]
Thanks! Works fine now.
