### ISSUE TITLE
ConnectAsHub Examples

### ISSUE THREAD

**Issue by marksouzacosta** [kolsrud/qlik_rest_sdk#13]
First of all, great work! This is helping me a lot these past days. Thank you very much.

It is not clear to me what is the **ConnectAsHub** is about. Can you please add some examples of it on the Examples folder?

Regards,
Mark Costa

**Comment by subramani-r-0595** [comment]
Hey @kolsrud Thanks a lot for building this. I am able to authenticate using NLTM. However, when trying to auth using "BasicConnectionCertificateFromFile" method, I am getting a 404 error. I am using the correct password for the .pfx file, but I am not sure what I am missing. Can you please help?

**Comment by kolsrud** [comment]
Wow... For some reason I didn't see this request until now. Sorry for the extremely long delay!

When you do "ConnectAsHub" then the RestClient will set the "Context" part of the security header. This controls whether the request should be considered as coming from the Hub or the QMC. This affects rule evaluation (and thereby what you are allowed to see) as a security rule can be set to affect access from only one of those sources.

Some more info on this header can be found here:

https://help.qlik.com/en-US/sense-developer/August2021/Subsystems/ProxyServiceAPI/Content/Sense_ProxyServiceAPI/ProxyServiceAPI-Injected-Req-Headers-X-Qlik-Security.htm
