### ISSUE TITLE
BasicConnectionCertificateFromFile Not working

### ISSUE THREAD

**Issue by CodeWithSubramani** [kolsrud/qlik_rest_sdk#15]
Hey @kolsrud  Thanks a lot for building this. I am able to authenticate using NLTM. However, when trying to auth using "BasicConnectionCertificateFromFile" method, I am getting a 404 error. I am using the correct password for the .pfx file, but I am not sure what I am missing. Can you please help?

**Comment by kolsrud** [comment]
Hard to say from this information, but 404 means "not found" so are you sure you are using the right URL? Perhaps you are adding a virtual proxy path in your URL also for the direct connection? If so, then remove that part as when you are doing direct connections then you bypass the proxy all together so virtual proxies are no longer relevant.

**Comment by CodeWithSubramani** [comment]
Thank you very much @kolsrud. After pointing the host name to the central node without any proxies, I was able to get this to work.
