### ISSUE TITLE
Problem with RestClient

### ISSUE THREAD

**Issue by victorvelasquez96** [kolsrud/qlik_rest_sdk#16]
Hi, 
sorry for the inconvenience.

I have an error on this part of the code that retrives the info of all apps:
`_var rsp = restClient.Get<JArray>("/qrs/app/hublist/full");_`

We i use this on my localhost it does work but on another server this is the response:
`_Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0._`

I tried to convert the response into an JObject or a Simple String but nothing works.

This Error is caused by Qlik?

Thanks

**Comment by kolsrud** [comment]
Hi! I've never run into that myself, but the error message seems to indicate that you are getting some invalid json there. What do you get if you just use the Get method without a type parameter, like this?
```
var rsp = restClient.Get("/qrs/app/hublist/full");
Console.WriteLine(rsp);
```

**Comment by kolsrud** [comment]
I see that I get a Json parse error if I am not correctly authenticated. So you should probably look at how you are setting up the authentication of your RestClient instance.

**Comment by victorvelasquez96** [comment]
Hi,
sorry if I answer only now.
They put a VirtualProxy so i can connect using the NTLM user info.

Someone has suggestions?

Thanks,
Victor

![MicrosoftTeams-image](https://user-images.githubusercontent.com/87643924/157012593-beb0c9f1-ebd5-41a6-9d07-e41c7e6112c9.png)

**Comment by victorvelasquez96** [comment]
> I see that I get a Json parse error if I am not correctly authenticated. So you should probably look at how you are setting up the authentication of your RestClient instance.

HI guys,
sorry if I answer only now.

Kolsrud was right, i'm unauthorized.

Question: could the virtual proxy present in the qmc be the problem? At the moment my connection is through NTLM data. I need to put in the URI-->https://ip/prefix?

**Comment by kolsrud** [comment]
@victorvelasquez96 The virtual proxy is what controls the authentication method, so if the default URL does not support NTLM, then you'll need to add the virtual proxy prefix to your URL like you suggest. So instead of
```
var client = new RestClient("https://ip");
```
you would need to do
```
var client = new RestClient("https://ip/prefix");
```
Then the rest of the flow will be the the same as before. So in your case it should probably look something like this:
```
var client = new RestClient("https://ip/prefix");
client.AsNtlmUserViaProxy();
var rsp = client.Get<JArray>("/qrs/app/hublist/full");
```

**Comment by victorvelasquez96** [comment]
Hi, 
@kolsrud 

Thanks for the advice! 

In my local host it works perfecty but on another server it gaves me this error-> (i use the vpn of the company, but the program is on the machine)


![1](https://user-images.githubusercontent.com/87643924/157071085-5438eac5-68f3-406b-b1cc-b5a3a9f4261d.png)

this is the setting of the proxy on the machine

![Screenshot_2](https://user-images.githubusercontent.com/87643924/157071260-145a8708-ab9e-40f4-959c-8cb27a296240.png)

My code ( i tried a simply "about"  but as you see the response it's different from a json like response):
```
 var senseServerUrl = domain;
           // ip = https://companyurl.domain.com/connect
            var uri = new Uri(senseServerUrl);
            var restClient = new RestClient(senseServerUrl);
            var networkCredentials = new NetworkCredential(user, password, userDomain);
            restClient.AsNtlmUserViaProxy(networkCredentials, certificateValidation:false);
           var rsp = restClient.Get("/qrs/about");
           Console.WriteLine(rsp);

```
Do you think that i need to modify the  header like this? -->

`restClient.CustomHeaders["XX-Qlik-Security"] = "Context=ManagementAccess";`

Thanks,
Victor

**Comment by kolsrud** [comment]
No, it's not necessary to change that header.

I take it the variable "domain" is equal to the value you have for "ip" in your comment?
What happens if you simply copy the "ip" you use to a browser? Does it work?

**Comment by victorvelasquez96** [comment]
> No, it's not necessary to change that header.
> 
> I take it the variable "domain" is equal to the value you have for "ip" in your comment? What happens if you simply copy the "ip" you use to a browser? Does it work?

Hi @kolsrud ,

Yes the domain variable is the IP Address, if i copy and paste it on the browser it gaves me error 404 (or it can't connect), it's strange because on other servers that has qlik it connects me directly on the hub.

To Turn around that problem we create another virtual proxy that use a Form.


Yesterday i see this article:
https://community.qlik.com/t5/App-Development/Qlik-Rest-APIs-gives-http-400-header-request-error-after/td-p/1668768

Do you think is related? Because the version of Qlik Sense is the **November 2019 Patch 5**

Thanks,
Victor

**Comment by kolsrud** [comment]
Are you sure the virtual proxy is correctly linked to a proxy? That's the first thing I would check if I were you:

https://help.qlik.com/en-US/sense-admin/February2022/Subsystems/DeployAdministerQSE/Content/Sense_DeployAdminister/QSEoW/Administer_QSEoW/Managing_QSEoW/link-virtual-proxy-to-proxy.htm

If it is, then updating the white-list is probably a good second thing to try.

**Comment by victorvelasquez96** [comment]
> Are you sure the virtual proxy is correctly linked to a proxy? That's the first thing I would check if I were you:
> 
> https://help.qlik.com/en-US/sense-admin/February2022/Subsystems/DeployAdministerQSE/Content/Sense_DeployAdminister/QSEoW/Administer_QSEoW/Managing_QSEoW/link-virtual-proxy-to-proxy.htm
> 
> If it is, then updating the white-list is probably a good second thing to try.

Sorry to respond this late.

I checked the article and i confirm that i setted in the same way:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/87643924/157292708-dc264cd2-2876-4750-a6ad-cc40e6c93051.png)

I put the hostname in the whitelist too:

![x](https://user-images.githubusercontent.com/87643924/157293131-73681bed-b559-4dee-ac74-abe817b3464e.jpg)

Now it returns two type of response:
The first is when i connect only with the IP and not the prefix : 401 unauthorized

The second one is when i use "IP/connect" (it uses the NTLM to log like the Main ,Central):

![xx](https://user-images.githubusercontent.com/87643924/157293555-92400b0e-0d89-4b23-9eea-fd46b49b1520.png)

it's like the same but this time without the 400 Error

**Comment by kolsrud** [comment]
Are you able to access your "connect" virtual proxy in a browser? I would suggest you focus on that first. If it doesn't work, then I would suggest you contact Qlik support to help you out with the configuration.

It could potentially be a firewall blocking your requests. In my experience a firewall will block the connection all together so that you simply get no response, but I did a quick search and it seems that there are cases where a firewall will trigger a 400 error. If you have access to the server, then you could try to run your program directly there. If that works, then there's certainly some for of server configuration you need to do to get it working.

**Comment by victorvelasquez96** [comment]
> Are you able to access your "connect" virtual proxy in a browser? I would suggest you focus on that first. If it doesn't work, then I would suggest you contact Qlik support to help you out with the configuration.
> 
> It could potentially be a firewall blocking your requests. In my experience a firewall will block the connection all together so that you simply get no response, but I did a quick search and it seems that there are cases where a firewall will trigger a 400 error. If you have access to the server, then you could try to run your program directly there. If that works, then there's certainly some for of server configuration you need to do to get it working.

Hi @kolsrud ,
yes i can connect using the virtural proxy.

Somehow i resolved the problem by using the ip address instead of the domain (ex. https://ipadress instead of https://namearea.domain.com), another thing was that i insert in the domain field on the network credentials an "/" because sometimes i used "./" in my local machine.

Sorry if i disturbed you.

Thanks,
Victor
