### ISSUE TITLE
Unable to read data from the transport connection: The connection was closed.

### ISSUE THREAD

**Issue by hp0123** [kolsrud/qlik_rest_sdk#2]
var restClient = new RestClient(senseServerUrl);
restClient.AsNtlmUserViaProxy(false);
Console.WriteLine(restClient.Post("/qrs/app/1fb52ebc-72cf-4552-9f60-a57261f24ae5/copy", "{\"appId\":\"1fb52ebc-72cf-4552-9f60-a57261f24ae5\"}"));

results in below exception

InnerException	{"Unable to read data from the transport connection: The connection was closed."}	System.Exception {System.IO.IOException}.

Along with copying, I am also trying to rename the app using below. How can it be done?

Console.WriteLine(restClient.Post("/qrs/app/1fb52ebc-72cf-4552-9f60-a57261f24ae5/copy?name=Test_newAppName", "{\"appId\":\"1fb52ebc-72cf-4552-9f60-a57261f24ae5\"}"));

System.Net.WebException: 'The request was aborted: Could not create SSL/TLS secure channel.'

Thanks!

**Comment by kolsrud** [comment]
I believe the problem you are seeing is the result of a bug in how the UriBuild.Query parameter is set when adding the XrefKey argument. It's the same thing that is described in this thread:

https://community.qlik.com/message/1425469

I thought I had already pushed that fix, but I guess not... It should be there now though, so use the latest version!

**Comment by hp0123** [comment]
Hi kolsrud,

I still get same error with the latest code, and also after removing query param from URL. Please see below.

var restClient = new RestClient(senseServerUrl);
restClient.AsNtlmUserViaProxy(false);
Console.WriteLine(restClient.Post("**/qrs/app/1fb52ebc-72cf-4552-9f60-a57261f24ae5/copy**", "{\"appId\":\"1fb52ebc-72cf-4552-9f60-a57261f24ae5\"}"));

**IOException: Unable to read data from the transport connection: The connection was closed.**

Get about ( cookie ) and Delete app works fine., but not the above post method.

Thanks!

**Comment by kolsrud** [comment]
The body of that POST operation should be empty. Do you get the same problem if you do like this?

`Console.WriteLine(restClient.Post("/qrs/app/1fb52ebc-72cf-4552-9f60-a57261f24ae5/copy", ""));`

**Comment by hp0123** [comment]
Ahh. Okay, it is fine and working after keeping body empty ( even with the param included in the URL ).

Thank you!

**Comment by kolsrud** [comment]
Good! Closing this then...
