### ISSUE TITLE
Info: ExportImg of an Object

### ISSUE THREAD

**Issue by victorvelasquez96** [kolsrud/qlik_rest_sdk#23]
Hi,
i have a question about Sense API.

This is the body of the request that i created (it works) wich exports an img of an object:

```
 var body = new
                {
                    type = "sense-image-1.0",
                    output = new
                    {
                       outputId = "imagecomposition",
                        type = "image",
                        imageOutput = new
                        {
                            outDpi = 96,
                            outFormat = "png"
                        }
                    },

                    senseImageTemplate = new
                    {
                        appId = appId,
                        visualization = new 
                        {
                            id = objectId,
                            widthPx = 2000,
                            heightPx = 2000
                        }                        
                    }
                };
```
So my question is:  
**there's another way to export the img without insert the pixel (width,height) of the object?**

Thanks,
Victor

**Comment by kolsrud** [comment]
Is this for the reporting API in QCS? I mean this one?

https://qlik.dev/apis/rest/reports

I'm not very familiar with those endpoints I'm afraid, and I would anyway suggest that you post your question on community. I'm sure the response would be of interest to a wider audience!

The forum to use would be "Integration, Extension & APIs": https://community.qlik.com/t5/Integration-Extension-APIs/bd-p/qlik-sense-integration-extension-api
