### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by rgluzman** [kolsrud/qlik_rest_sdk#5]
Hello
Great job you've done
I'm trying these script

restClient.Post("/qrs/task/start", "7117d556-0ff8-4f35-a8ce-fe9d2061c53f")
I have an error "Unable to create SSL/TLS channel"
Is there anything to configure with certificate to work fine please ?

Regards

Regis

**Comment by kolsrud** [comment]
Thanks! I've just added two examples that illustrate how to use the library with certificates. One that collects the certificates from the local store, and one where the certificates are collected from a directory.

**Comment by rgluzman** [comment]
Thanks a lot

Le jeudi 11 octobre 2018, Øystein Kolsrud <notifications@github.com> a
écrit :
