### ISSUE TITLE
Dynamic Hash and Token

### ISSUE THREAD

**Issue by srivasha** [kolsrud/qlik_rest_sdk#9]
Hi, Can this REST support generation of Dynamic Token value using system data and HASH value? Sorry this is not an issue but a query?
Thanks

**Comment by kolsrud** [comment]
Sorry for the late response, didn't see this message until now...

The library is primarily intended for accessing the Qlik Sense services for Qlik Sense Enterprise for Windows which includes the Repository, Proxy and Scheduler services. Support for anything outside of that is by accident only :-)

So focus is in these API:s: https://help.qlik.com/en-US/sense-developer/November2019/Content/Sense_Helpsites/APIs-and-SDKs.htm
